name: Build and push to store
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
        - amd64
        - armhf
        - arm64
    steps:
    - uses: actions/checkout@v2
    - name: Snapcraft
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.platform }}
      id: snapcraft-build
      env:
        TERM: dumb
    - name: Publish
      uses: snapcore/action-publish@v1
      env:
        TERM: dumb
      with:
        store_login: ${{ secrets.SNAPCRAFT_LOGIN }}
        snap: ${{ steps.snapcraft-build.outputs.snap }}
        release: edge
    - name: Promote stable versions
      run: |
        snap_file=${{ steps.snapcraft-build.outputs.snap }}
        snap_name=$(echo "$snap_file" | grep "[a-z0-9]\+_" -o | head -1 | sed "s/_//")
        if echo "$snap_file" | grep -q "[a-z0-9]\+_[0-9.]\+_.*\.snap"; then
          echo "Stable version of $snap_name found, so let's promote it"
          last_revision=$(snapcraft list-revisions $snap_name \
            --arch="$(dpkg --print-architecture)" | \
              head -n2 | tail -n1 | cut -f1 -d ' ')
          snapcraft release $snap_name $last_revision stable
        fi
